### ISSUE TITLE
Merge with Modular Scale

### ISSUE THREAD

**Issue by robsonsobral** [jeremychurch/type-scale#10]
From https://github.com/modularscale/modularscale.com/issues/81

> Hi!
>
> Both [Modular Scale](http://www.modularscale.com/) and @jeremychurch's [Type-scale](http://type-scale.com/) are almost perfect. **Type-scale** has the load of Google Fonts, the font-family and weight customizations and the preview panel. **Modular Scale** has the Sass plugin, the JS code and the multiple bases.
>
> Can't the both be merged? The strengths of Type-Scale could be added to Modular Scale and to become an amazing tool!
>
> Thank you for your attention, everybody.

**Comment by robsonsobral** [comment]
Since there's no interest on merge the projects, do you mind if I add more scales, @jeremychurch ?

**Comment by jeremychurch** [comment]
Oh, I already added a feature for custom scales back in 2014 ( pull request #8 ), so users can enter any scale they want :)

I don't think I would add any more options to the select list, though. I think I actually removed a few around the same time, because they were so similar or too big.

![screenshot-2017-11-8 type scale - a visual calculator](https://user-images.githubusercontent.com/471793/32557574-ccf9f810-c45f-11e7-92e5-574fafe1033e.png)

**Comment by robsonsobral** [comment]
I see. I'm just trying to make it easier to use for the other designers here. It's easier for them to have options. They prefer the multiple options of the Modular Scale, but the Type Scale preview.

Sorry, for bother you.

Thanks, man!

**Comment by jeremychurch** [comment]
Yep! No bother. I always like hearing the feedback :)
